package ternary_operator;

import java.util.Scanner;

public class to_14 {
    public static void main(String[]args){
        Scanner sc=new Scanner(System.in);
        int q = sc.nextInt();
        if(q==1){System.out.println("I");}
        if(q==2){System.out.println("II");}
        if(q==3){System.out.println("III");}
        if(q==4){System.out.println("IV");}
        if(q==5){System.out.println("V");}
        if(q==6){System.out.println("VI");}
        if(q==7){System.out.println("VII");}
        if(q==8){System.out.println("VIII");}
        if(q==9){System.out.println("IX");}
        if(q==10){System.out.println("X");}
        if(q==11){System.out.println("XI");}
        if(q==12){System.out.println("XII");}
        if(q==13){System.out.println("XIII");}
        if(q==14){System.out.println("XIV");}
        if(q==15){System.out.println("XV");}
        if(q==16){System.out.println("XVI");}
        if(q==17){System.out.println("XVII");}
        if(q==18){System.out.println("XVIII");}
        if(q==19){System.out.println("XIX");}
        if(q==20){System.out.println("XX");}
        if(q==21){System.out.println("XXI");}
        if(q==22){System.out.println("XXII");}
        if(q==23){System.out.println("XXIII");}
        if(q==24){System.out.println("XXIV");}
        if(q==25){System.out.println("XXV");}
        if(q==26){System.out.println("XXVI");}
        if(q==27){System.out.println("XXVII");}
        if(q==28){System.out.println("XXVIII");}
        if(q==29){System.out.println("XXIX");}
        if(q==30){System.out.println("XXX");}
        if(q==31){System.out.println("XXXI");}
        if(q==32){System.out.println("XXXII");}
        if(q==33){System.out.println("XXXIII");}
        if(q==34){System.out.println("XXXIV");}
        if(q==35){System.out.println("XXXV");}
        if(q==36){System.out.println("XXXVI");}
        if(q==37){System.out.println("XXXVII");}
        if(q==38){System.out.println("XXXVIII");}
        if(q==39){System.out.println("XXXIX");}
        if(q==40){System.out.println("XL");}
        if(q==41){System.out.println("XLI");}
        if(q==42){System.out.println("XLII");}
        if(q==43){System.out.println("XLIII");}
        if(q==44){System.out.println("XLIV");}
        if(q==45){System.out.println("XLV");}
        if(q==46){System.out.println("XLVI");}
        if(q==47){System.out.println("XLVII");}
        if(q==48){System.out.println("XLVIII");}
        if(q==49){System.out.println("XLIX");}
        if(q==50){System.out.println("L");}
        if(q==51){System.out.println("LI");}
        if(q==52){System.out.println("LII");}
        if(q==53){System.out.println("LIII");}
        if(q==54){System.out.println("LIV");}
        if(q==55){System.out.println("LV");}
        if(q==56){System.out.println("LVI");}
        if(q==57){System.out.println("LVII");}
        if(q==58){System.out.println("LVIII");}
        if(q==59){System.out.println("LIX");}
        if(q==60){System.out.println("LX");}
        if(q==61){System.out.println("LXI");}
        if(q==62){System.out.println("LXII");}
        if(q==63){System.out.println("LXIII");}
        if(q==64){System.out.println("LXIV");}
        if(q==65){System.out.println("LXV");}
        if(q==66){System.out.println("LXVI");}
        if(q==67){System.out.println("LXVII");}
        if(q==68){System.out.println("LXVIII");}
        if(q==69){System.out.println("LXIX");}
        if(q==70){System.out.println("LXX");}
        if(q==71){System.out.println("LXXI");}
        if(q==72){System.out.println("LXXII");}
        if(q==73){System.out.println("LXXIII");}
        if(q==74){System.out.println("LXXIV");}
        if(q==75){System.out.println("LXXV");}
        if(q==76){System.out.println("LXXVI");}
        if(q==77){System.out.println("LXXVII");}
        if(q==78){System.out.println("LXXVIII");}
        if(q==79){System.out.println("LXXIX");}
        if(q==80){System.out.println("LXXX");}
        if(q==81){System.out.println("LXXXI");}
        if(q==82){System.out.println("LXXXII");}
        if(q==83){System.out.println("LXXXIII");}
        if(q==84){System.out.println("LXXXIV");}
        if(q==85){System.out.println("LXXXV");}
        if(q==86){System.out.println("LXXXVI");}
        if(q==87){System.out.println("LXXXVII");}
        if(q==88){System.out.println("LXXXVIII");}
        if(q==89){System.out.println("LXXXIX");}
        if(q==90){System.out.println("XC");}
        if(q==91){System.out.println("XCI");}
        if(q==92){System.out.println("XCII");}
        if(q==93){System.out.println("XCIII");}
        if(q==94){System.out.println("XCIV");}
        if(q==95){System.out.println("XCV");}
        if(q==96){System.out.println("XCVI");}
        if(q==97){System.out.println("XCVII");}
        if(q==98){System.out.println("XCVIII");}
        if(q==99){System.out.println("LXCIX");}
        if(q==100){System.out.println("C");}
    }
}
